"""
data/reference/columns_order.py
Ordre exact des colonnes pour chaque table archivée.

Les fichiers d'archive (.txt) sont produits par Sage ERP via COPY PostgreSQL.
Ils ne contiennent PAS d'en-tête. Les colonnes doivent être assignées
dans le même ordre que la définition SQL (cf. postgres/init_db_test.sql).

Format du fichier archive : {TABLE}_{YYYYMMDD}_{HHMMSS}.txt
Séparateur               : tabulation
Encodage                 : UTF-8 avec ou sans BOM (auto-détecté)
"""

COLUMNS_ORDER: dict[str, list[str]] = {
    "F_ARTSTOCK": [
        "ar_ref",
        "as_qtesto",
        "de_no",
    ],
    "F_ARTICLE": [
        "ar_ref",
        "ar_design",
        "fa_codefamille",
        "ar_uniteven",
        "ar_prixach",
        "ar_prixven",
        "ar_prixttc",
        "ar_suivistock",
        "ar_codebarre",
        "ar_punet",
        "ar_coutstd",
        "ar_type",
        "ar_nature",
        "ar_sommeil",
    ],
    "F_DEPOT": [
        "de_no",
        "de_intitule",
    ],
    "F_LOTSERIE": [
        "ar_ref",           
        "ls_noserie",       
        "ls_peremption",    
        "ls_qte",           
        "ls_lotepuise",     
        "ls_qterestant",    
        "de_no",            
    ],
    "F_FAMILLE": [
        "fa_codefamille",
        "fa_type",
        "fa_intitule",
        "fa_uniteven",
        "fa_suivistock",
        "fa_central",
    ],
    "P_UNITE": [
        "u_intitule",       
        "cbindice",         
    ],
    "F_COMPTET": [
        "ct_num",
        "ct_intitule",
        "ct_type",
        "cg_numprinc",
        "ct_qualite",
        "ct_contact",
        "ct_adresse",
        "ct_complement",
        "ct_ville",
        "ct_coderegion",
        "ct_identifiant",
        "ct_telephone",
        "ct_telecopie",
        "ct_email",
        "ct_site",
        "co_no",
        "cbcreation",
        "ct_sommeil",
    ],
    "F_COLLABORATEUR": [
        "co_no",
        "co_nom",
        "co_prenom",
        "co_fonction",
        "co_vendeur",
        "co_acheteur",
        "co_telephone",
        "co_telecopie",
        "co_email",
        "co_matricule",
    ],
    "F_DOCENTETE": [
        "do_domaine",
        "do_type",
        "do_piece",
        "do_date",
        "do_ref",
        "do_tiers",
        "co_no",
        "do_totalht",
        "do_totalhtnet",
        "do_totalttc",
        "do_montantregle",
        "do_escompte",
    ],
    "F_DOCLIGNE": [
        "do_domaine",       
        "do_type",          
        "ct_num",           
        "do_piece",         
        "dl_piecebc",       
        "dl_piecebl",       
        "do_date",          
        "dl_datebc",        
        "dl_datebl",        
        "dl_ligne",         
        "do_ref",          
        "ar_ref",           
        "dl_design",        
        "dl_qte",           
        "dl_qtebc",         
        "dl_qtebl",         
        "dl_prixunitaire",  
        "co_no",            
        "dl_prixru",        
        "dl_cmup",          
        "dl_puttc",         
        "dl_no",            
        "dl_valorise",      
        "dl_nonlivre",      
        "dl_montantht",     
        "dl_montantttc",    
        "pf_num",          
        "dl_datede",        
        "dl_qtede",         
        "dl_montanthtnet",  
        "dl_montantttcnet", 
    ],
    "F_REGLECH": [
        "rg_no",            
        "dr_no",            
        "do_domaine",       
        "do_type",          
        "do_piece",         
        "rc_montant",       
        "rg_typereg",       
    ],
}

COLUMNS_COUNT: dict[str, int] = {k: len(v) for k, v in COLUMNS_ORDER.items()}
